version: '3.1'

services:

  wordpress:
    image: wordpress
    user: 1000:1000
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp_dev
      WORDPRESS_DB_PASSWORD: wp_dev
      WORDPRESS_DB_NAME: wp_dev
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', 'http://localhost:8080');
        define('WP_SITEURL', 'http://localhost:8080');
    volumes:
      - ./wp:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wp_dev
      MYSQL_USER: wp_dev
      MYSQL_PASSWORD: wp_dev
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - db:/var/lib/mysql

  pma:
    image: phpmyadmin
    restart: always
    ports:
      - 8888:80

volumes:
  db:
